### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by zmraul**
Addresses [DPE-1008](https://warthogs.atlassian.net/browse/DPE-1008).

Change docs to follow current readme scheme. 

[DPE-1008]: https://warthogs.atlassian.net/browse/DPE-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by deusebio** [comment]
Great work! I just noticed that in the [ticket](https://warthogs.atlassian.net/browse/DPE-1008) I was also referring to these points to be fixed (raised months ago after seeing docs status in charmhub): 

> Refecence/Libraries: [cluster](hhttps://charmhub.io/zookeeper-k8s/libraries/cluster?channel=edge) module missing documentation

**question** I'm not sure why this module is rendered in charmhub because I don't see it in the repo. Could it be a problem of charmhub? If so, we should probably open an issue [here](https://github.com/canonical/charmhub.io/issues) 
  
> Refecence/Configuration: Remove log-dir and data-dir, these configuration should not be there

**out-of-scope** I believe this point would require a bit of refactoring (changing also the code) which may be beyond the scope of this PR. I believe it is not so interesting to expose these parameters (also given charms should not exposed parameters which we could figure out). We should however place a ticket in the backlog 

> Reference/Actions: explain what sync and super password means. Now the documentation is not very clear.

**todo** I'd say

**Review by welpaolo — DISMISSED** [review]
Great improvement!

**Comment by zmraul** [comment]
> > Refecence/Libraries: cluster module missing documentation
> 
> **question** I'm not sure why this module is rendered in charmhub because I don't see it in the repo. Could it be a problem of charmhub? If so, we should probably open an issue [here](https://github.com/canonical/charmhub.io/issues)

This is most likely because the libs exist on the `latest/stable` channel. When you click on any of them on charmhub, the site automatically changes to the `stable` url instead of staying on the `edge` one. Maybe this is a bug on charmhub, I'll open the issue.

> > Reference/Actions: explain what sync and super password means. Now the documentation is not very clear.
> 
> **todo** I'd say

@deusebio Should this be done on the readme, or in the description for the action itself?

**Comment by deusebio** [comment]
In the yaml file is fine. The description there is really too minimal I feel, and makes it somewhat not clear what sync and super is

**Review by welpaolo — APPROVED** [review]
Looks great!

**Review by deusebio — APPROVED** [review]

**Comment by marcoppenheimer** [comment]
@deusebio lib was removed here - https://github.com/canonical/zookeeper-k8s-operator/commit/09daf0e71c9d3c4eda7ede8f79a6a48f0d5b899b

It's hard to clear up old libs from charmhub apparently

**Pull request merged**
